id = "luau"
name = "Luau"
version = "0.3.8"
schema_version = 1
authors = ["teapo <4teapo@gmail.com>"]
description = "Luau support."
repository = "https://github.com/4teapo/zed-luau"

[language_servers.luau-lsp]
name = "Luau LSP"
language = "Luau"

[grammars.luau]
repository = "https://github.com/4teapo/tree-sitter-luau"
commit = "ab4a4c15076486ff8981df73e988ffeaa22bd3ca"
