name = "Luau"
grammar = "luau"
path_suffixes = ["luau"]
line_comments = ["-- "]
autoclose_before = ";:.,=}])>"
first_line_pattern = "^#!.*\b(lune|luau|zune)\b"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [ "comment", "string" ] },
    { start = "'", end = "'", close = true, newline = false, not_in = [ "comment", "string" ] },
    { start = "`", end = "`", close = true, newline = false, not_in = [ "comment", "string" ] },
    { start = "<", end = ">", close = false, newline = false, not_in = [ "comment", "string" ] },
    { start = "then", end = "end", close = false, newline = true, not_in = [ "comment", "string" ] },
    { start = "do", end = "end", close = false, newline = true, not_in = [ "comment", "string" ] },
    { start = "function", end = "end", close = false, newline = true, not_in = [ "comment", "string" ] },
    { start = "repeat", end = "until", close = false, newline = true, not_in = [ "comment", "string" ] },
]
collapsed_placeholder = "--[ ... ]--"
